"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.appRouterV1 = void 0;
const controllers_1 = require("../../controllers");
const userRouter_1 = __importDefault(require("./userRouter"));
const myProfileRouter_1 = __importDefault(require("./myProfileRouter"));
const scheduleRouter_1 = __importDefault(require("./scheduleRouter"));
const storeRouter_1 = __importDefault(require("./storeRouter"));
const attendanceRouter_1 = __importDefault(require("./attendanceRouter"));
const statisticRouter_1 = __importDefault(require("./statisticRouter"));
const locationRouter_1 = __importDefault(require("./locationRouter"));
const attendanceHistoryRouter_1 = __importDefault(require("./attendanceHistoryRouter"));
const authRouter_1 = __importDefault(require("./authRouter"));
const adminRouter_1 = __importDefault(require("./adminRouter"));
const apiVersion = '/api/v1';
const appRouterV1 = (app) => {
    app.get(apiVersion, async (req, res) => await (0, controllers_1.index)(req, res));
    app.use(apiVersion + '/users', userRouter_1.default);
    app.use(apiVersion + '/schedules', scheduleRouter_1.default);
    app.use(apiVersion + '/my-profile', myProfileRouter_1.default);
    app.use(apiVersion + '/stores', storeRouter_1.default);
    app.use(apiVersion + '/attendances', attendanceRouter_1.default);
    app.use(apiVersion + '/attendances/histories', attendanceHistoryRouter_1.default);
    app.use(apiVersion + '/statistic', statisticRouter_1.default);
    app.use(apiVersion + '/locations', locationRouter_1.default);
    app.use(apiVersion + '/auth', authRouter_1.default);
    app.use(apiVersion + '/admins', adminRouter_1.default);
};
exports.appRouterV1 = appRouterV1;
