"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const middlewares_1 = require("../../middlewares");
const employee_1 = require("../../controllers/employee");
const employeeLocation_1 = require("../../controllers/employeeLocation");
const router = (0, express_1.Router)();
router.get('/', middlewares_1.middleware.useAuthorization, async (req, res) => await employee_1.employeeController.findAll(req, res));
router.get('/detail/:employeeId', middlewares_1.middleware.useAuthorization, middlewares_1.middleware.allowRoles('admin', 'superAdmin'), async (req, res) => await employee_1.employeeController.findDetail(req, res));
router.patch('/', middlewares_1.middleware.useAuthorization, middlewares_1.middleware.allowRoles('admin', 'superAdmin'), async (req, res) => await employee_1.employeeController.update(req, res));
router.get('/locations', middlewares_1.middleware.useAuthorization, async (req, res) => await employeeLocation_1.employeeLocationController.findAll(req, res));
router.post('/locations', middlewares_1.middleware.useAuthorization, async (req, res) => await employeeLocation_1.employeeLocationController.create(req, res));
exports.default = router;
