"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.appRouterV1 = void 0;
const appCheckRouter_1 = __importDefault(require("./appCheckRouter"));
const employeeRouter_1 = __importDefault(require("./employeeRouter"));
const authRouter_1 = __importDefault(require("./authRouter"));
const storeRouter_1 = __importDefault(require("./storeRouter"));
const scheduleRouter_1 = __importDefault(require("./scheduleRouter"));
const scheduleSwapRouter_1 = __importDefault(require("./scheduleSwapRouter"));
const attendanceRouter_1 = __importDefault(require("./attendanceRouter"));
const attendanceHistoryRouter_1 = __importDefault(require("./attendanceHistoryRouter"));
const adminRouter_1 = __importDefault(require("./adminRouter"));
const statisticRouter_1 = __importDefault(require("./statisticRouter"));
const myProfileRouter_1 = __importDefault(require("./myProfileRouter"));
const storeLocationRouter_1 = __importDefault(require("./storeLocationRouter"));
const otpRouter_1 = __importDefault(require("./otpRouter"));
const resetDeviceRouter_1 = __importDefault(require("./resetDeviceRouter"));
const reportRouter_1 = __importDefault(require("./reportRouter"));
const apiVersion = '/api/v1';
const appRouterV1 = (app) => {
    app.use(apiVersion, appCheckRouter_1.default);
    app.use(apiVersion + '/employees', employeeRouter_1.default);
    app.use(apiVersion + '/auth', authRouter_1.default);
    app.use(apiVersion + '/stores', storeRouter_1.default);
    app.use(apiVersion + '/schedules', scheduleRouter_1.default);
    app.use(apiVersion + '/schedule-swaps', scheduleSwapRouter_1.default);
    app.use(apiVersion + '/attendances', attendanceRouter_1.default);
    app.use(apiVersion + '/attendance-histories', attendanceHistoryRouter_1.default);
    app.use(apiVersion + '/admins', adminRouter_1.default);
    app.use(apiVersion + '/statistic', statisticRouter_1.default);
    app.use(apiVersion + '/my-profiles', myProfileRouter_1.default);
    app.use(apiVersion + '/store-locations', storeLocationRouter_1.default);
    app.use(apiVersion + '/otp', otpRouter_1.default);
    app.use(apiVersion + '/reset-devices', resetDeviceRouter_1.default);
    app.use(apiVersion + '/reports', reportRouter_1.default);
};
exports.appRouterV1 = appRouterV1;
